apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: dapr
spec:
  workflows:
    promise:
      configure:
      - apiVersion: platform.kratix.io/v1alpha1
        kind: Pipeline
        metadata:
          name: promise-configure
        spec:
          containers:
          - image: ghcr.io/syntasso/kratix-marketplace/dapr-configure-pipeline:v0.1.0
            name: dapr-promise-pipeline
