apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: argocd-application
spec:
  api:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: argocd-applications.marketplace.kratix.io
    spec:
      group: marketplace.kratix.io
      names:
        kind: argocd-application
        plural: argocd-applications
        singular: argocd-application
      scope: Namespaced
      versions:
      - name: v1alpha1
        schema:
          openAPIV3Schema:
            properties:
              spec:
                properties:
                  source:
                    description: Source is a reference to the location of the application's
                      manifests or chart
                    properties:
                      path:
                        default: .
                        description: Path is a directory path within the Git repository,
                          and is only valid for applications sourced from Git. The
                          default path is the root directory.
                        type: string
                      repoURL:
                        description: RepoURL is the URL to the repository (Git or
                          Helm) that contains the application manifests. This URL
                          must be public.
                        type: string
                      targetRevision:
                        description: TargetRevision defines the revision of the source
                          to sync the application to. In case of Git, this can be
                          commit, tag, or branch. If omitted, will equal to HEAD.
                        type: string
                    required:
                    - repoURL
                    type: object
                required:
                - source
                type: object
            type: object
        served: true
        storage: true
  workflows:
    promise:
      configure:
      - apiVersion: platform.kratix.io/v1alpha1
        kind: Pipeline
        metadata:
          name: promise-configure
        spec:
          containers:
          - image: ghcr.io/syntasso/kratix-marketplace/argocd-application-configure-pipeline:v0.1.0
            name: argocd-app-promise-pipeline
    resource:
      configure:
      - apiVersion: platform.kratix.io/v1alpha1
        kind: Pipeline
        metadata:
          name: instance-configure
        spec:
          containers:
          - image: ghcr.io/syntasso/kratix-marketplace/argocd-application-configure-pipeline:v0.1.0
            name: argocd-application-configure-pipeline
