apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  creationTimestamp: null
  name: kubevela
spec:
  workflows:
    promise:
      configure:
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: promise-configure
          spec:
            containers:
              - image: ghcr.io/syntasso/kratix-marketplace/kubevela-configure-pipeline:v0.1.0
                name: kubevela-configure-pipeline
    resource: {}
status: {}
