apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: kubeflow-pipelines
spec:
  api:
    apiVersion: apiextensions.k8s.io/v1alpha1
    kind: CustomResourceDefinition
    metadata:
      name: kfpipelines.marketplace.kratix.io
    spec:
      group: marketplace.kratix.io
      names:
        kind: kfpipelines
        plural: kfpipelines
        singular: kfpipelines
      scope: Namespaced
      versions:
      - name: v1
        schema:
          openAPIV3Schema:
            properties: {}
            type: object
        served: true
        storage: true
  workflows:
    promise:
      configure:
      - apiVersion: platform.kratix.io/v1alpha1
        kind: Pipeline
        metadata:
          name: promise-configure
        spec:
          containers:
          - image: ghcr.io/syntasso/kratix-marketplace/kubeflow-pipelines-configure-pipeline:v0.1.0
            name: promise-configure-pipeline
    resource:
      configure:
      - apiVersion: platform.kratix.io/v1alpha1
        kind: Pipeline
        metadata:
          name: instance-configure
        spec:
          containers:
          - image: ghcr.io/syntasso/kratix-marketplace/kubeflow-pipelines-configure-pipeline:v0.1.0
            name: kubeflow-pipelines-configure-pipeline
