apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: vault
spec:
  api:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: vaults.marketplace.kratix.io
    spec:
      group: marketplace.kratix.io
      names:
        kind: vault
        plural: vaults
        singular: vault
      scope: Namespaced
      versions:
        - name: v1alpha1
          schema:
            openAPIV3Schema:
              properties:
                spec:
                  properties:
                    env:
                      default: dev
                      description:
                        "Configures and deploys this Vault with environment
                        specific configuration. For dev we auto-unseal the Vault instance.
                        For we leave the Vault instance sealed. \n"
                      pattern: ^(dev|prod)$
                      type: string
                  type: object
              type: object
          served: true
          storage: true
  workflows:
    resource:
      configure:
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: instance-configure
          spec:
            containers:
              - image: ghcr.io/syntasso/kratix-marketplace/vault-configure-pipeline:v0.1.0
                name: vault-configure-pipeline
