apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: knative
spec:
  api:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: knatives.marketplace.kratix.io
    spec:
      group: marketplace.kratix.io
      names:
        kind: knative
        plural: knatives
        singular: knative
      scope: Namespaced
      versions:
      - name: v1alpha1
        schema:
          openAPIV3Schema:
            properties:
              spec:
                properties:
                  env:
                    default: dev
                    description: |
                      Configures and deploys this Knative with environment specific configuration.
                      Prod Knative enables application autoscaling using HPA.
                    pattern: ^(dev|prod)$
                    type: string
                type: object
            type: object
        served: true
        storage: true
  workflows:
    promise:
      configure:
      - apiVersion: platform.kratix.io/v1alpha1
        kind: Pipeline
        metadata:
          name: promise-configure
        spec:
          containers:
          - image: ghcr.io/syntasso/kratix-marketplace/knative-configure-pipeline:v0.1.0
            name: knative-promise-pipeline
    resource:
      configure:
      - apiVersion: platform.kratix.io/v1alpha1
        kind: Pipeline
        metadata:
          name: instance-configure
        spec:
          containers:
          - image: ghcr.io/syntasso/kratix-marketplace/knative-configure-pipeline:v0.1.0
            name: knative-configure-pipeline
