apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: vaultnamespace
spec:
  api:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: vaultnamespaces.marketplace.kratix.io
    spec:
      group: marketplace.kratix.io
      names:
        kind: VaultNamespace
        plural: vaultnamespaces
        singular: vaultnamespace
      scope: Namespaced
      versions:
        - name: v1alpha1
          schema:
            openAPIV3Schema:
              properties:
                spec:
                  properties:
                    kubernetes:
                      properties:
                        caCert:
                          description: kubernetse ca certificate
                          type: string
                        host:
                          description: kubernetes address
                          type: string
                      type: object
                    team:
                      description: The team name
                      type: string
                  required:
                    - team
                    - kubernetes
                  type: object
              type: object
          served: true
          storage: true
  destinationSelectors:
  - matchLabels:
      environment: platform
  workflows:
    resource:
      configure:
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: instance-configure
          spec:
            rbac:
              permissions:
              - apiGroups:
                  - ""
                resourceNames:
                  - vault
                resourceNamespace: default
                resources:
                  - configmaps
                verbs:
                  - get
            containers:
              - image: ghcr.io/syntasso/kratix-marketplace/vault-namespace-configure-pipeline:v0.1.0
                name: vault-namespace-configure-pipeline
