apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  creationTimestamp: null
  name: cert-manager
  labels:
    kratix.io/promise-version: v1.0.0-beta.1
spec:
  workflows:
    promise:
      configure:
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: promise-configure
          spec:
            containers:
              - image: ghcr.io/syntasso/kratix-marketplace/cert-manager-configure-pipeline:v0.1.0
                name: certmanager-configure-pipeline
    resource: {}
status: {}
